name: socialapp
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_conditional_rendering: ^2.0.0
  fluttertoast: ^8.0.8
  hexcolor: ^2.0.5
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
